const caseTemplate = 
{OK:true,
 "data":
       {"id":null,
      	"type":null,
      	"original_language":null,
      	"post_date":null,
      	"published":null,
      	"updated_date":null,
      	"location":
              {"name":null,
               "address1":null,
               "address2":null,
               "city":null,
               "province":null,
               "country":null,
               "postal_code":null,
               "latitude":null,
               "longitude":null
              },
      	"files":
	       {"url": null,
		"title": null,
		"size": null},
      	"tags":null,
      	"featured":null,
      	"issue":null,
      	"communication_mode":null,
      	"communication_with_audience":null,
      	"content_country":null,
      	"decision_method":null,
      	"end_date":null,
      	"facetoface_online_or_both":null,
      	"facilitated":null,
      	"voting":null,
      	"number_of_meeting_days":null,
      	"ongoing":null,
      	"start_date":null,
      	"total_number_of_participants":null,
	"targeted_participant_demographic":null,
      	"kind_of_influence":null,
      	"targeted_participants_public_role":null,
      	"targeted_audience":null,
      	"participant_selection":null,
	"specific_topic":null,
	"staff_type":null,
	"type_of_funding_entity":null,
	"typical_implementing_entity":null,
	"typical_sponsoring_entity":null,
	"who_else_supported_the_initiative":null,
	"who_was_primarily_responsible_for_organizing_the_initiative":null,
	"links":null,
	"hidden":null,
	"videos":null,
	"images":null,
	"body":null,
	"title":null,
	"authors":
		 {"user_id":null,
		  "timestamp":null,
		  "name":null},
	"related_cases":null,
	"related_methods":null,
	"related_organizations":null,
	"bookmarked":null}
}

const methodTemplate = 
{OK:true,
 "data":
       {"id":null,
        "type":null,
        "original_language":null,
	"post_date":null,
	"published":null,
	"updated_date":null,
	"location":
		{"name":null,
		"address1":null,
		"address2":null,
		"city":null,
		"province":null,
		"country":null,
		"postal_code":null,
		"latitude":null,
		"longitude":null},
	"files":
        {"url": null,
		"title": null,
		"size": null},
	"tags":null,
	"featured":null,
	"best_for":null,
	"communication_mode":null,
	"decision_method":null,
	"facilitated":null,
	"governance_contribution":null,
	"issue_interdependency":null,
	"issue_polarization":null,
	"issue_technical_complexity":null,
	"kind_of_influence": null,
	"method_of_interaction":null,
	"public_interaction_method":null,
	"typical_funding_source":null,
	"typical_implementing_entity":null,
	"typical_sponsoring_entity": null,
	"links": null,
	"hidden":null,
	"videos":null,
	"images":null,
	"body":null,
	"title": null,
	"authors":
		{"user_id":null,
		 "timestamp":null,
		 "name":null},
	"related_cases":null,
	"related_methods":null,
	"related_organizations":null,
	"bookmarked":null}
}

const organizationTemplate = 
{ OK:true,
 "data":
	{"id":null,
	 "type": null,
	"original_language":null,
	"post_date":null,
	"published":null,
	"updated_date":null,
	"location": {
		"name":null,
		"address1":null,
		"address2":null,
		"city":null,
		"province":null,
		"country":null,
		"postal_code":null,
		"latitude": null,
		"longitude": null},
	"files":
        {"url": null,
		"title": null,
		"size": null},
	"tags":null,
	"featured":null,
	"executive_director":null,
	"issue":null,
	"sector":null,
	"links":null,
	"hidden":null,
	"videos":null,
	"images":null,
	"body": null,
	"authors": {
		"user_id":null,
		"timestamp":null,
		"name":null},
	"related_cases":null,
	"related_methods":null,
	"related_organizations":null,
	"bookmarked":null}

}

module.exports = {
  caseTemplate,
  methodTemplate,
  organizationTemplate
};
